I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 869, in script
    邻居 "早啊，听说你媳妇生了？怎么样？男孩女孩？"
Exception: Sayer '邻居' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 869, in script
    邻居 "早啊，听说你媳妇生了？怎么样？男孩女孩？"
  File "F:\WorkSpace\Game\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "F:\WorkSpace\Game\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "F:\WorkSpace\Game\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '邻居' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.3.24061702
Gm 1.0
Wed Aug  7 13:08:19 2024
